#!/bin/bash

IPV4_IPS="$(curl -s https://www.cloudflare.com/ips-v4)"
IPV6_IPS="$(curl -s https://www.cloudflare.com/ips-v6)"

echo -n "" > /etc/nginx/cloudflare.conf

for ip in ${IPV4_IPS}; do
	echo "set_real_ip_from ${ip};" >> /etc/nginx/cloudflare.conf
done

for ip in ${IPV6_IPS}; do
	echo "set_real_ip_from ${ip};" >> /etc/nginx/cloudflare.conf
done

echo "real_ip_header CF-Connecting-IP;" >> /etc/nginx/cloudflare.conf

cat /etc/nginx/cloudflare.conf
